language: ruby
sudo: false
rvm:
  - 1.9.3
  - jruby-19mode
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem update bundler

matrix:
  allow_failures:
    - rvm: jruby-19mode

notifications:
  email: false
